# Generated by Django 4.2 on 2023-05-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="card_id", new_name="cart_id",
        ),
    ]
